// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlWZ-qusaWhycG2ZSUu-59rwSgP3zhhg',
    appId: '1:177324161829:web:1683fee66f9c66f00bf8cc',
    messagingSenderId: '177324161829',
    projectId: 'minimalchat-eb6a8',
    authDomain: 'minimalchat-eb6a8.firebaseapp.com',
    storageBucket: 'minimalchat-eb6a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqX-RzcQyU4DXvyFwigYSCU43wA3ORmgU',
    appId: '1:177324161829:android:eaaea3d8fab00f720bf8cc',
    messagingSenderId: '177324161829',
    projectId: 'minimalchat-eb6a8',
    storageBucket: 'minimalchat-eb6a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJofEqALbT5yBo2dq73u4zGFdJY4AXSg',
    appId: '1:177324161829:ios:8f446e47f6c8f1970bf8cc',
    messagingSenderId: '177324161829',
    projectId: 'minimalchat-eb6a8',
    storageBucket: 'minimalchat-eb6a8.appspot.com',
    iosBundleId: 'com.example.minimalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJofEqALbT5yBo2dq73u4zGFdJY4AXSg',
    appId: '1:177324161829:ios:8f446e47f6c8f1970bf8cc',
    messagingSenderId: '177324161829',
    projectId: 'minimalchat-eb6a8',
    storageBucket: 'minimalchat-eb6a8.appspot.com',
    iosBundleId: 'com.example.minimalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQlWZ-qusaWhycG2ZSUu-59rwSgP3zhhg',
    appId: '1:177324161829:web:241a1e98a54beb630bf8cc',
    messagingSenderId: '177324161829',
    projectId: 'minimalchat-eb6a8',
    authDomain: 'minimalchat-eb6a8.firebaseapp.com',
    storageBucket: 'minimalchat-eb6a8.appspot.com',
  );
}
